DROP DATABASE IF EXISTS SPOWNER;
CREATE DATABASE SPOWNER;
USE SPOWNER;

CREATE TABLE spowner.pet
(
    ID      int         NOT NULL AUTO_INCREMENT,
    NAME    VARCHAR(75) NOT NULL,
    OWNER   VARCHAR(75) NOT NULL,
    SPECIES VARCHAR(75) NOT NULL,
    SEX     CHAR(1),
    BIRTH   DATE,
    DEATH   DATE,
    CONSTRAINT PET_ID_PK PRIMARY KEY (ID)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;